// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqoidqrpuidkfaweizik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxb2lkcXJwdWlka2Zhd2VpemlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2OTY3NTAsImV4cCI6MjA4NjI3Mjc1MH0.svtGunOoxTOYwwOJ0gijMTCLuxTEfpSWGgOLcyBHo_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});